# Workflow for running checks on pull requests to the main branch
name: PR Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read # To read the repo

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
